[package]
name = "rusiwebov"
version = "0.1.0"
authors = ["fly2moon2 <fly2moon2@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.5"
regex = "0.1.41"
